GET http://localhost:4004/odata/v4/data/sales
###

POST http://localhost:4004/odata/v4/data/sales
Content-Type: application/json

{
  "date": "2026-10-15",
  "sales": 800
}
###

GET http://localhost:4004/odata/v4/ai/ask
Content-Type: application/json

{
  "question": "Hi"
}